### ISSUE TITLE
Conflict with tmux

### ISSUE THREAD

**Issue by pasantru** [Hyzeta/vim_equinusocio_material#1]
When installing the plugin as instructed on the readme with plugin. And following the how to use notes, when I start vim on a tmux session it does not properly render the colorscheme.

**Comment by yunlingz** [comment]
> When installing the plugin as instructed on the readme with plugin. And following the how to use notes, when I start vim on a tmux session it does not properly render the colorscheme.

Please make sure you have configured tmux to support true color properly. For example, if your `$TERM` is `xterm-256color`, then you should add these lines in your `~/.tmux.conf`:

```
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
```

Or you should try this:

```
set -g default-terminal "${TERM}"
set -ga terminal-overrides ",${TERM}:Tc"
```

And please provide your `~/.tmux.conf` (and maybe `.vimrc`), so I can reproduce your bug if there is any. Thanks.

**Comment by pasantru** [comment]
Perfect I has screen-256colors. Maybe you can update the readme. Thanks for the help.

**Comment by oblitum** [comment]
FYI, `:RGB` is preferred over `:Tc` in latest tmux versions (so called "official"): https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour.

**Comment by oblitum** [comment]
`set -ga terminal-overrides ',*:RGB'` is sufficient to have it applied for any terminal, not one in specific. On recent systems a tmux installation comes with its own terminfo which is preferred over `xterm-256color`/`screen-256color`. This is what I use in Arch for example:

```
set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',*:RGB'
```
