### ISSUE TITLE
Less contrast on pure style

### ISSUE THREAD

**Issue by oblitum** [Hyzeta/vim_equinusocio_material#4]
Hi, nice colorscheme!

I was looking for a colorscheme with very dark background and the pure style of this theme looks great. One issue though, the contrast is too high and may make one eyes bleed. What about keeping the background tone but making foreground less bright?

**Comment by yunlingz** [comment]
Emmm...  Good idea...

I shall create a new style `pure_less`.

**Comment by oblitum** [comment]
It seems that even the darker variant suffers from this, specially regarding the white text.

**Comment by yunlingz** [comment]
> It seems that even the darker variant suffers from this, specially regarding the white text.

New option: `g:equinusocio_material_less`

```viml
" less bright
" which means some foreground color will be modified by this formula:
" (r, g, b) -> ( max(r - less, 0), max(g - less, 0), max(b - less, 0) )
let g:equinusocio_material_less = 50
```

**Comment by oblitum** [comment]
Nice!
