### ISSUE TITLE
diff mode doesn't use background highlighting to show changes

### ISSUE THREAD

**Issue by leonardt** [Hyzeta/vim_equinusocio_material#5]
Using neovim (in case it's relevant)
```
❯ nvim --version
NVIM v0.4.3
```

Config
```
let g:equinusocio_material_style = 'pure'
colorscheme equinusocio_material
```

File 1 (a.txt)
```
this line is only in a
this line is in both
this line has one char different (a)
```

File 2 (b.txt)
```
this line is in both
this line has one char different (b)
this line is only in b
```

The result of doing `nvim -d a.txt b.txt`
![image](https://user-images.githubusercontent.com/3766436/89440546-9ea7f280-d700-11ea-9fd3-8f8e23954ee8.png)

Here's the same diff using the Nord theme
![image](https://user-images.githubusercontent.com/3766436/89440628-bed7b180-d700-11ea-8ee8-5a845cfb09d1.png)

I'm not sure if this choice was deliberate, but for complex diffs, it's pretty hard to see the changes since they're just different text colors (it almost just looks like syntax highlighting when quickly scanning files).  When looking at diffs, I find the background highlighting showing the changes (and type of change, e.g. different character on same line, missing line) useful for quickly seeing what the class of differences are.

Feel free to close if this is by design (although perhaps we could make using background colors an option?)

**Comment by yunlingz** [comment]
I'll take a look at it.

**Comment by yunlingz** [comment]
Now it works like Nord theme, please update to the latest version.

![image](https://user-images.githubusercontent.com/23468295/89715352-c4224e00-d9d7-11ea-9721-9488c03bf9de.png)

**Comment by leonardt** [comment]
look great, thanks!
